server:
  port: 8082
  
spring:
  application:
    name: PRODUCT-SERVICE  
  zipkin:
    base-url: http://localhost:9411  
  sleuth:
    sampler:
     probability: 1.0  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka       